/**
 * Auto-generated by scripts/stamp_webapp_build.js — do not edit by hand.
 */
export const BUILD_INFO = {
  id: "919f557@2026-08-02T08:40:05.656Z",
  short: "919f557",
  full: "919f557b0d4c984861a2b4b60251149deba01050",
  stampedAt: "2026-08-02T08:40:05.656Z",
  note: 'branch Pages: open /web-app/ and check this id',
};
