/**
 * Auto-generated by scripts/stamp_webapp_build.js — do not edit by hand.
 */
export const BUILD_INFO = {
  id: "d1e75b4@2026-08-02T09:31:22.093Z",
  short: "d1e75b4",
  full: "d1e75b453a00a756c0288c734e60c72097fbacff",
  stampedAt: "2026-08-02T09:31:22.093Z",
  note: 'branch Pages: open /web-app/ and check this id',
};
