/** Write web-app/build-info.js + cache-bust index.html from current git HEAD */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const web = path.join(ROOT, 'web-app');

let short = 'unknown';
let full = 'unknown';
try {
  short = execSync('git rev-parse --short HEAD', { cwd: ROOT }).toString().trim();
  full = execSync('git rev-parse HEAD', { cwd: ROOT }).toString().trim();
} catch {
  /* ignore */
}

const stampedAt = new Date().toISOString();
const body = `/**
 * Auto-generated by scripts/stamp_webapp_build.js — do not edit by hand.
 */
export const BUILD_INFO = {
  id: ${JSON.stringify(short + '@' + stampedAt)},
  short: ${JSON.stringify(short)},
  full: ${JSON.stringify(full)},
  stampedAt: ${JSON.stringify(stampedAt)},
  note: 'branch Pages: open /web-app/ and check this id',
};
`;

fs.writeFileSync(path.join(web, 'build-info.js'), body);

// Cache-bust CSS/JS on index.html
let html = fs.readFileSync(path.join(web, 'index.html'), 'utf8');
html = html
  .replace(/href="\.\/style\.css(\?v=[^"]*)?"/, `href="./style.css?v=${short}"`)
  .replace(/src="\.\/main\.js(\?v=[^"]*)?"/, `src="./main.js?v=${short}"`);
fs.writeFileSync(path.join(web, 'index.html'), html);

console.log('stamped', short, stampedAt);
